[chapter-1]
scene = [
  { id = "equilateralTriangle", distance = "foreground", placement = "center", color = "blue", mood = "happy" },
  { id = "circle", distance = "aboveground", placement = "right", color = "pink", mood = "happy" },
  { id = "rectangle", distance = "foreground", placement = "left", color = "blue", mood = "neutral" },
  { id = "square", distance = "foreground", placement = "right", color = "green", mood = "happy" },
  { id = "scaleneTriangle", distance = "background", placement = "center", color = "green", mood = "neutral" },
  { id = "trapezoid", distance = "midground", placement = "center", color = "pink", mood = "happy" }
]
intro = [
  { speaker= "equilateralTriangle", text = "Hi! Welcome to Shapes!" },
  { speaker = "player", text = "… … … Uhm, hi? Where am I?"},
  { speaker = "equilateralTriangle", text = "Just take a look - you are in Shapes, a world is governed by the rules of geometry." },
  { speaker = "player", text = "In the immortal words of Keanu Reeves...whoaaaa. So. Now what?" },
  { speaker = "equilateralTriangle", text = "Well, recently my friends and I have been disagreeing about how our world of Shapes works. Maybe you could help us settle our disagreements?" },
  { speaker = "player", text = "Sure, I guess...where do you want to start?" },
  { speaker = "equilateralTriangle", text = "Well, in Shapes, we care about being in shape. So, before we talk ideas, let's get up and move around!" },
  { speaker = "player", text = "Jeez, you're demanding. So, what do I have to do?" },
  { speaker = "equilateralTriangle", text = "Simply follow my movements to stay in shape! Click next and let's get started!" }
]
outro = [
  { speaker = "equilateralTriangle", text = "OOPS! You found a bug! Sorry about that. Click next to progress." },
  { speaker = "equilateralTriangle", text = "Thanks, that was really helpful!" },
  { speaker = "player", text = 'I guess I am! What next?' },
  { speaker = "equilateralTriangle", text = "Hmmm, I think circle wanted to chat about something..." },
  { speaker = "equilateralTriangle", text = "Thanks for trying out the latest prototype of The Hidden Village online! Future versions will include experimental tasks for participants to perform, alongside experiment planning and pose editing tools." },
]
completionAnimation = [
  { id = "equilateralTriangle", moveTo = "background center", animation = "triangle_waving" }
]

[chapter-2]
intro = [
  { speaker = "circle", text = "What are you??" },
  { speaker = "player", text = "That's...kind of a rude greeting. Nice to meet you, too. I heard you wanted to chat about something?" },
  { speaker = "circle", text = "Oh yeah -- triangle and I were chatting, but came to an impasse. Click next so I can show you what I mean!" },
]
outro = []
