[chapter-1]
scene = [
  { id = "equilateralTriangle", distance = "foreground", placement = "center", color = "blue", mood = "happy" },
  { id = "circle", distance = "aboveground", placement = "right", color = "pink", mood = "happy" },
  { id = "rectangle", distance = "foreground", placement = "left", color = "blue", mood = "neutral" },
  { id = "square", distance = "foreground", placement = "right", color = "green", mood = "happy" },
  { id = "scaleneTriangle", distance = "background", placement = "center", color = "green", mood = "neutral" },
  { id = "trapezoid", distance = "midground", placement = "center", color = "pink", mood = "happy" }
]
intro = [
  { speaker= "equilateralTriangle", text = "Hello?" },
  { speaker = "player", text = "… … … Uhm, hi? Where am I?"},
  { speaker = "equilateralTriangle", text = "You're in Shape" },
  { speaker = "player", text = "I am?" },
  { speaker = "equilateralTriangle", text = "Yes. Just take a look! You are in Shapes!" },
  { speaker = "player", text = "Oh my goodness. I am!" },
  { speaker = "equilateralTriangle", text = "Yes... Triangles! Circles! Quadralaterals!" },
  { speaker = "player", text = "Ok, so now what?" },
  { speaker = "equilateralTriangle", text = "Well, in order to be in shape, you have to get in shape!" },
  { speaker = "player", text = "What do I have to do to get in shape?" },
  { speaker = "equilateralTriangle", text = "Simply follow my movements to stay in shape! Let's get started!" }
]
outro = [
  { speaker = "equilateralTriangle", text = "Thanks for trying out the latest prototype of The Hidden Village online! Future versions will include experimental tasks for participants to perform, alongside experiment planning and pose editing tools." },
  { speaker = "equilateralTriangle", text = "Wow! You’re speedy. Look at that!" },
  { speaker = "player", text = 'I guess I am! Any idea where I should go next?' },
  { speaker = "equilateralTriangle", text = "I’m not sure. It’s all the same around here, but maybe it’ll all come together the more you are inside?" }
]
completionAnimation = [
  { id = "equilateralTriangle", moveTo = "background center", animation = "triangle_waving" }
]

[chapter-2]
intro = []
outro = []
