[tutorial]
instructions = [
  { text = "Welcome to The Hidden Village!\n Let's calibrate your image for the best-quality gameplay." },
  { text ="Move away from the screen so that your body can be seen in the screen. You may wish to adjust the angle of your webcam." },
  { text = "Match the pose on the left...", pose_id = "tutorial_pose_1" },
  { text = "Match the pose on the left again...", pose_id = "tutorial_pose_2" },
  { text = "One more time -- match the pose on the left...", pose_id = "cursor_pose" },
  { text = "Using your right hand, move the cursor to the  arrow at the bottom of the screen to progress" }
]
transitionText = "Great"

[intro]
narrative = [
  {text = "נסיון ראשון לגבי האם זה עובד בכלל"},
  {text = "Hey! You there! I haven't seen you around here before... what ARE you??"},
  {text = "Huh...a person?! What's that?? That's the strangest sound name for a shape that I'VE ever encountered."},
  {text = "I've got to say, though... It's pretty cool what you're doing with the sides of your shape..."},
  {text = "In this world, our sides don't change, but it looks like yours do! I think it's quite inspiring!"},
  {text = "Show me one of your moves!"}
]

